### ISSUE TITLE
Question about applying CRF for your init seed mask?

### ISSUE THREAD

**Issue by TyroneLi** [jbeomlee93/AdvCAM#11]
Could u offer more implementation details about this part?

**Comment by jbeomlee93** [comment]
We first generate a segmentation mask similar to the below. We set a background threshold to 0.3 or 0.35, but not sure.

https://github.com/jbeomlee93/AdvCAM/blob/fa08f0ad4c1f764f3ccaf36883c0ae43342d34c5/step/eval_cam.py#L18-L20

We then apply CRFs with pydensecrf library. You can refer to [https://github.com/kazuto1011/deeplab-pytorch/blob/4219467fa5de07985f834f1bd8c04c186dc8f6d8/main.py#L482] for more details.
