### ISSUE TITLE
Performance Gap on Init Seed

### ISSUE THREAD

**Issue by PlumedSerpent** [jbeomlee93/AdvCAM#16]
Hi, I ran your codes and apply all the hyper-parameters by default. But the init seed mIoU is only 48.75, which is reported as 55.6 in your paper. I wonder if i miss something? Here is my train command line:
CUDA_VISIBLE_DEVICES=4,5,6,7 python run_sample.py --voc12_root Dataset/VOC2012_SEG_AUG/   --cam_out_dir result/cam_res50 --sem_seg_out_dir result/seg_res50 --ir_label_out_dir result/ir_label_res50 --irn_weights_name sess/res50_irn.pth    --make_ins_seg_pass False --eval_ins_seg_pass False 

And here is my init seed result:

![image](https://user-images.githubusercontent.com/11538323/140858326-0c21994b-06eb-491b-9c97-33bd7eea2cae.png)

**Comment by jbeomlee93** [comment]
Hi, 

To obtain the initial seed of AdvCAM, you should run "obtain_CAM_masking.py", not "run_sample.py".

Please refer to "get_seed_quality.sh"

https://github.com/jbeomlee93/AdvCAM/blob/fa08f0ad4c1f764f3ccaf36883c0ae43342d34c5/get_seed_quality.sh#L3-L4

Thanks.

**Comment by PlumedSerpent** [comment]
> Hi,
> 
> To obtain the initial seed of AdvCAM, you should run "obtain_CAM_masking.py", not "run_sample.py".
> 
> Please refer to "get_seed_quality.sh"
> 
> https://github.com/jbeomlee93/AdvCAM/blob/fa08f0ad4c1f764f3ccaf36883c0ae43342d34c5/get_seed_quality.sh#L3-L4
> 
> Thanks.

Got it, thanks.
