### ISSUE TITLE
how to visualize the loss landscape?

### ISSUE THREAD

**Issue by seyeeet** [jbeomlee93/AdvCAM#3]
in the paper you mentioned and showed an example of visualizing the loss landscape.
Can you please explain how to do it ?
 I would really appreciate it if you can share the code for that since I am new to this topic and your implementation will be super useful!

**Comment by jbeomlee93** [comment]
Hi @seyeeet, the loss landscape was visualized through the following process.

1. For an image x, compute the classification loss L(x).
2. Compute vec{n} by backward L, and obtain any random vector vec{r}.
3. Compute L(x+alpha\*vec{n}+beta\*vec{r}). -1<beta<1, alpha>0: adversarial attack, alpha<0: adversarial climbing
4. Plot (alpha, beta, L(x+alpha\*vec{n}+beta\*vec{r}))

Thanks!

**Comment by seyeeet** [comment]
Thanks for your explanation, it is more  clear now.
Can you please explain a little more how to compute `vec{n}` and `vec{r}` and what is the shape of `vec{n}` and `vec{r}`.
I mean what `vec{n}` means, I mean what is the dimension of `vec` and are `n` and `r` integers?
Sorry I am new to this and your explanation is very helpful

**Comment by jbeomlee93** [comment]
vec{n} and vec{r} are actually matrices with the same spatial size as the input image.

vec{n} is a gradient map of classification loss L with respect to an image, which can be obtained similar to the following:
https://github.com/jbeomlee93/AdvCAM/blob/fa08f0ad4c1f764f3ccaf36883c0ae43342d34c5/obtain_CAM_masking.py#L138-L142

vec{r} is literally a random matrix.

Thanks.

**Comment by seyeeet** [comment]
thank you
