### ISSUE TITLE
combine with seam

### ISSUE THREAD

**Issue by lzyhha** [jbeomlee93/AdvCAM#7]
Hello, thanks for your great work. I notice that you have combine the AdvCAM with SEAM in paper. Could you please teel me how ti combine them?

**Comment by jbeomlee93** [comment]
Hi @lzyhha, I downloaded pre-trained model of SEAM at the official SEAM repository (https://github.com/YudeWang/SEAM), and applied adversarial climbing similar to `obtain_CAM_masking.py`.

We observed that the values of the optimal hyper-parameters differ according to the backbone network, especially $T$ and $\lambda$. SEAM and SC-CAM used Wide ResNet-38. I'm not sure, but I think $T$ was 8 and $\lambda$ was 2.

**Comment by lzyhha** [comment]
Thanks! Your reply is very helpful.

**Comment by YeRen123455** [comment]
Hi @lzyhha ！ 
I notice that you can reproduce the result of "adv_cam+SEAM" by yourself. Can you share the code with me? Thanks a lot!
