### ISSUE TITLE
Question about Table 4.

### ISSUE THREAD

**Issue by hchoi71** [jbeomlee93/AdvCAM#8]
Thanks for sharing this great work!

Just wondering if you could also share the code that reproduces table 4, especially AdvCAM with SEAM. 

I found the SEAM GitHub and I assume that your AdvCAM should be replaced with cam in SEAM code as shown in the below link
[https://github.com/YudeWang/SEAM/blob/c55601649c5fa676836d3ec70ec044541b7d1d83/network/resnet38_SEAM.py#L32] 

Could you please guide me on how to merge your AdvCAM into the SEAM module? 

Thanks

**Comment by jbeomlee93** [comment]
Hi @hchoi71,

I downloaded pre-trained model of SEAM at the official SEAM repository (https://github.com/YudeWang/SEAM), and applied adversarial climbing similar to obtain_CAM_masking.py.

More specifically, adversarial climbing was done on logit, GAP(cam), before up-sampled and before PCM module.

We then accumulate our localization maps (in Equation 4) using CAM after PCM module.

Thanks.
